### PR TITLE
Renamed SpringLambdacontainerHandler to SpringLambdaContainerHandler

### PR DESCRIPTION
**Pull request by joeyvmason**

### CODE REVIEW

**Comment by SAPessi** [comment]
Thanks, I totally missed this. Can you confirm that the unit tests still run ok.

**Comment by SAPessi** [comment]
Also, I see in your spring boilerplate project that you created your own WebApplicationInitializer, would it make sense to let you pass an initializer to the container handler class instead of having our own in the background?

**Comment by joeyvmason** [comment]
Yes can confirm project still builds and all tests pass.

**Comment by joeyvmason** [comment]
In regard to the WebApplicationInitializer, that could work but I'm not sure just yet. Need to spend more time getting familiar with this library.

**Pull request merged**
