### PR TITLE
Provide ApplicationContext instead of Config classes

### PR DESCRIPTION
**Pull request by joeyvmason**
Added ability to provide custom ApplicationContext. For Spring testing, made objects that can potentially be shared by multiple tests classes and methods beans.

### CODE REVIEW

**Comment by SAPessi** [comment]
In the latest commit I've added the ability to initialize the library with an implementation of WebApplicationContext, would that work?

**Comment by joeyvmason** [comment]
It's a little more complicated than just adding this. The main issue is that if you are using an applicationContext generated by Spring when running tests, making a call to `refresh()` will cause the test to fail because `refresh()` can only be called once. 

The other fix here is that the tests were not using the Spring test framework, which I think is important because that's how Spring developers are going to be using this library. By adding that, I was able to catch the refresh issue above. I also made the `SpringLambdaContainerHandler` a bean because this object needs to be shared by multiple test classes. If you try to initialize two instances of it, it will fail because both instances will try to update the shared `applicationContext`.

**Comment by SAPessi** [comment]
I see, makes sense. The only change I would suggest from your last commit is that we don't use the refreshContext boolean as a constructor parameter, instead we create a setter for it. This way, the constructor remains clean and simple with a single parameter and you can call the setter only from your unit tests - the default value for refreshContext is true. What do you think?

**Comment by joeyvmason** [comment]
Sure makes sense. Just pushed changes for this.

**Pull request merged**
