### PR TITLE
Add ALB Context to API GW Payload V2

### PR DESCRIPTION
**Pull request by driverpt**
*Issue #489*

*Description of changes:*
Adds ALB Context to Request Context. [Source](https://docs.aws.amazon.com/lambda/latest/dg/services-alb.html)

By submitting this pull request

- [ X ] I confirm that my contribution is made under the terms of the Apache 2.0 license.
- [ X ] I confirm that I've made a best effort attempt to update all relevant documentation.

### CODE REVIEW

**Comment by driverpt** [comment]
Done

**Comment by driverpt** [comment]
Any ETA on this one ?

**Comment by deki** [comment]
On my list for this week, first tests were successful.

We may switch to aws-lambda-java-events lib in the future and I'm wondering about this:
https://github.com/aws/aws-lambda-java-libs/blob/events-v4-serialization-v2/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/ApplicationLoadBalancerRequestEvent.java

**Comment by driverpt** [comment]
Alb request is pretty much the same as Payload V2. I also agree this lib should be switched to use Events Library, but that would probably be a breaking change.

**Comment by deki** [comment]
Yeah that's a 2.0 thing, we will not do it now. I was just thinking that it is probably not enough to have a single event (like in aws-lambda-java-events lib) but we rather need ApplicationLoadBalancerRequestEventV1 and ApplicationLoadBalancerRequestEventV2, don't we?

**Comment by driverpt** [comment]
@deki , I think that SRP (Single Responsibility Principle) should be applied where possible, as in, 1 Event = 1 Class

**Comment by driverpt** [comment]
@deki , do you want me to change to separate events and apply SRP ?

**Comment by deki** [comment]
No let's keep it like this for know and refactor for 2.0.

**Pull request merged**
